"""``testo init`` — interactive wizard for a starter testosterone.yaml."""

from __future__ import annotations

import json
from pathlib import Path

import typer


def wizard(
    path: Path | None = typer.Option(
        None,
        "--path",
        help="Output path (prompted when omitted).",
    ),
) -> None:
    """Interactive scaffolding for a default testosterone.yaml (non-interactive: use ``testo config init``)."""
    from testo_core.cli.ui.console import default_console
    from testo_core.cli.ui.feedback import print_fail, print_ok

    console = default_console()
    out = path
    if out is None:
        out = Path(typer.prompt("Output file", default="testosterone.yaml")).expanduser()
    out = out.expanduser().resolve()

    if out.exists():
        overwrite = typer.confirm(f"{out} exists — overwrite?", default=False)
        if not overwrite:
            print_fail(console, "Aborted.")
            raise typer.Exit(code=2)

    target_repo = typer.prompt("Default target_repo (relative to config dir)", default=".")
    artifacts = typer.prompt("artifacts_root", default="artifacts")
    workers = int(typer.prompt("Default workers", default="4"))
    timeout_s = int(typer.prompt("Default timeout_s", default="600"))
    cycle_name = typer.prompt("First cycle name", default="smoke")
    db_url = typer.prompt("database.url (optional, leave empty to skip)", default="", show_default=False)
    db_block = ""
    if str(db_url).strip():
        db_block = f"database:\n  url: {json.dumps(str(db_url).strip())}\n\n"

    yaml_text = f"""version: 1
{db_block}defaults:
  target_repo: {json.dumps(str(Path(target_repo)))}
  artifacts_root: {json.dumps(str(artifacts))}
  timeout_s: {timeout_s}
  workers: {workers}

cycles:
  {cycle_name}:
    description: Generated by ``testo init``.
    tags: [smoke]
    stages:
      - name: api
        equipment: pytest
        args: ["-q", "--maxfail=1", "tests"]
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(yaml_text, encoding="utf-8")
    print_ok(console, f"Wrote {out}")
    raise typer.Exit(code=0)
